#!/usr/bin/env node
// Refresh workspace/memory/INDEX.md — the always-in-context distillation of Helm's memory.
// Imported by CLAUDE.md so every claude run boots with the latest facts + learned preferences.
// Regenerated by the background think daemon and after consolidation. Edit memory via memory.mjs.

import { DatabaseSync } from 'node:sqlite';
import { writeFileSync, renameSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const db = new DatabaseSync(path.join(__dirname, 'memory.db'));

// Bug fix: ensure episodes table exists before querying — refresh-index may run
// before memory.mjs has ever been imported (which is the only other creator of this table).
db.exec(`CREATE TABLE IF NOT EXISTS episodes (
  id      INTEGER PRIMARY KEY AUTOINCREMENT,
  ts      INTEGER NOT NULL DEFAULT (unixepoch()),
  channel TEXT,
  summary TEXT NOT NULL,
  raw_ref TEXT
)`);

const facts = db.prepare(
  `SELECT kind, key, value, confidence, updated FROM facts ORDER BY kind, confidence DESC, updated DESC`
).all();
const prefs = facts.filter(f => f.kind === 'preference');
const others = facts.filter(f => f.kind !== 'preference');
const episodes = db.prepare(`SELECT ts, channel, summary FROM episodes ORDER BY ts DESC LIMIT 12`).all();
const fmt = u => new Date(u * 1000).toISOString().slice(0, 16).replace('T', ' ');

let md = `# Helm memory index\n`;
md += `_Auto-generated ${new Date().toISOString()}. Do not hand-edit; change via \`node workspace/memory/memory.mjs\`._\n\n`;

md += `## Owner preferences (actively learned)\n`;
md += (prefs.length
  ? prefs.map(p => `- **${p.key}**: ${p.value}  _(conf ${Number(p.confidence).toFixed(2)})_`).join('\n')
  : '- (none yet)') + '\n\n';

md += `## Key facts\n`;
const byKind = {};
for (const f of others) (byKind[f.kind] ??= []).push(f);
for (const k of Object.keys(byKind).sort()) {
  md += `\n### ${k}\n` + byKind[k].slice(0, 30).map(f => `- **${f.key}**: ${f.value}`).join('\n') + '\n';
}
if (!others.length) md += '- (none yet)\n';

md += `\n## Recent episodes\n`;
md += (episodes.length
  ? episodes.map(e => `- ${fmt(e.ts)} [${e.channel || '-'}] ${e.summary}`).join('\n')
  : '- (none)') + '\n';

// Bug fix: write atomically via a temp file so a crash mid-write never leaves
// INDEX.md in a corrupted/truncated state (it is imported by every Claude session).
const indexPath = path.join(__dirname, 'INDEX.md');
const tmpPath   = indexPath + '.tmp';
writeFileSync(tmpPath, md);
renameSync(tmpPath, indexPath);
db.close();
console.log(`INDEX.md refreshed: ${facts.length} facts (${prefs.length} prefs), ${episodes.length} episodes`);
